### ISSUE TITLE
Cranium build broken

### ISSUE THREAD

**Issue by jjaskulowski** [sbatman/Cranium#8]
s_batman: your check-in broke DNA.cs

**Comment by jjaskulowski** [comment]
Hotfix: 
public T GetGene<T>(String name) where T : Gene
        {
            return (T)_Genes[name];
        }

**Comment by sbatman** [comment]
Cheers, ill look into fixing up these issues over the next day or so :D

**Comment by sbatman** [comment]
Resolved in : b10647cf3bf179d126dc1fb9e872646db621fc0c
